In [ ]:
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE



In [ ]:
#reading the data
data = pd.read_csv("creditcard.csv")
data.shape

(284807, 31)

In [ ]:
#separating the data into independent and depenent variable
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [ ]:
#removing oversampling
over_sampler = SMOTE(sampling_strategy="minority")
X_oversampled, Y_oversampled = over_sampler.fit_resample(x, y)


In [ ]:
#filling the missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x)
x = imputer.transform(x)

In [ ]:
print(x)

[[ 0.00e+00 -1.36e+00 -7.28e-02 ...  1.34e-01 -2.11e-02  1.50e+02]
 [ 0.00e+00  1.19e+00  2.66e-01 ... -8.98e-03  1.47e-02  2.69e+00]
 [ 1.00e+00 -1.36e+00 -1.34e+00 ... -5.54e-02 -5.98e-02  3.79e+02]
 ...
 [ 1.73e+05  1.92e+00 -3.01e-01 ...  4.45e-03 -2.66e-02  6.79e+01]
 [ 1.73e+05 -2.40e-01  5.30e-01 ...  1.09e-01  1.05e-01  1.00e+01]
 [ 1.73e+05 -5.33e-01 -1.90e-01 ... -2.42e-03  1.36e-02  2.17e+02]]


In [ ]:
#Feature extraction
import statsmodels.api as sm
X = np.append(arr = np.ones((284807, 1)).astype(int), values = x, axis = 1)
X_opt = X[:, [0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15,16,1,7,18,19,20,21,22,23,24,25,26,27,28,29,30]]
X_opt = X_opt.astype(np.float64)
print(X_opt)

[[ 1.00e+00  0.00e+00 -1.36e+00 ...  1.34e-01 -2.11e-02  1.50e+02]
 [ 1.00e+00  0.00e+00  1.19e+00 ... -8.98e-03  1.47e-02  2.69e+00]
 [ 1.00e+00  1.00e+00 -1.36e+00 ... -5.54e-02 -5.98e-02  3.79e+02]
 ...
 [ 1.00e+00  1.73e+05  1.92e+00 ...  4.45e-03 -2.66e-02  6.79e+01]
 [ 1.00e+00  1.73e+05 -2.40e-01 ...  1.09e-01  1.05e-01  1.00e+01]
 [ 1.00e+00  1.73e+05 -5.33e-01 ... -2.42e-03  1.36e-02  2.17e+02]]


In [ ]:
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Class   R-squared:                       0.483
Model:                            OLS   Adj. R-squared:                  0.483
Method:                 Least Squares   F-statistic:                     9178.
Date:                Wed, 16 Aug 2023   Prob (F-statistic):               0.00
Time:                        08:42:23   Log-Likelihood:             5.9594e+05
No. Observations:              284807   AIC:                        -1.192e+06
Df Residuals:                  284777   BIC:                        -1.192e+06
Df Model:                          29                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0017      0.000      9.803      0.000       0.001       0.002
x1         -4.103e-09   8.08e-10     -5.080      0.000   -5.69e-09   -2.52e-09
x2            -0.0019   3.67e-05    -51.032      0.000      -0.002      -0.002
x3             0.0030   7.12e-05     41.979      0.000       0.003       0.003
x4            -0.0051   5.06e-05   -100.704      0.000      -0.005      -0.005
x5             0.0037   4.22e-05     88.580      0.000       0.004       0.004
x6            -0.0022   6.85e-05    -32.128      0.000      -0.002      -0.002
x7            -0.0009   2.63e-05    -32.867      0.000      -0.001      -0.001
x8            -0.0070   7.74e-05    -89.867      0.000      -0.007      -0.007
x9             0.0009   4.98e-05     17.380      0.000       0.001       0.001
x10           -0.0036   5.15e-05    -70.057      0.000      -0.004      -0.004
x11           -0.0081   5.45e-05   -147.783      0.000      -0.008      -0.008
x12            0.0062   5.79e-05    107.217      0.000       0.006       0.006
x13           -0.0108   5.68e-05   -189.367      0.000      -0.011      -0.011
x14           -0.0002   5.65e-05     -4.039      0.000      -0.000      -0.000
x15           -0.0132   5.93e-05   -223.039      0.000      -0.013      -0.013
x16           -0.0003    6.3e-05     -4.167      0.000      -0.000      -0.000
x17        -4.103e-09   8.08e-10     -5.080      0.000   -5.69e-09   -2.52e-09
x18           -0.0009   2.63e-05    -32.867      0.000      -0.001      -0.001
x19           -0.0160   6.62e-05   -241.838      0.000      -0.016      -0.016
x20           -0.0056   6.78e-05    -82.236      0.000      -0.006      -0.005
x21            0.0019   7.01e-05     27.653      0.000       0.002       0.002
x22            0.0001      0.000      0.910      0.363      -0.000       0.000
x23            0.0020   8.13e-05     24.538      0.000       0.002       0.002
x24            0.0003   8.05e-05      3.940      0.000       0.000       0.000
x25            0.0002   9.64e-05      2.534      0.011    5.53e-05       0.000
x26           -0.0005   9.24e-05     -5.670      0.000      -0.001      -0.000
x27            0.0003      0.000      2.525      0.012    6.45e-05       0.001
x28            0.0004      0.000      3.138      0.002       0.000       0.001
x29            0.0016      0.000     11.837      0.000       0.001       0.002
x30            0.0011      0.000      6.611      0.000       0.001       0.001
x31         8.666e-06   7.79e-07     11.131      0.000    7.14e-06    1.02e-05
==============================================================================
Omnibus:                   593594.746   Durbin-Watson:                   1.973
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       5942385671.781
Skew:                          17.542   Prob(JB):                         0.00
Ku

In [ ]:
#all features are important since p(t)<0.5
X_opt = X[:, [0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15,16,1,7,18,19,20,21,23,24,26,27,28,29,30]]
X_opt = X_opt.astype(np.float64)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Class   R-squared:                       0.482
Model:                            OLS   Adj. R-squared:                  0.482
Method:                 Least Squares   F-statistic:                     9813.
Date:                Wed, 16 Aug 2023   Prob (F-statistic):               0.00
Time:                        08:42:25   Log-Likelihood:             5.9562e+05
No. Observations:              284807   AIC:                        -1.191e+06
Df Residuals:                  284779   BIC:                        -1.191e+06
Df Model:                          27                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0009      0.000      5.241      0.000       0.001       0.001
x1         -2.798e-09   8.07e-10     -3.468      0.001   -4.38e-09   -1.22e-09
x2            -0.0017    3.6e-05    -47.015      0.000      -0.002      -0.002
x3             0.0035   6.79e-05     51.791      0.000       0.003       0.004
x4            -0.0048   4.95e-05    -97.614      0.000      -0.005      -0.005
x5             0.0036    4.2e-05     86.463      0.000       0.004       0.004
x6            -0.0018   6.61e-05    -26.615      0.000      -0.002      -0.002
x7            -0.0010   2.58e-05    -38.558      0.000      -0.001      -0.001
x8            -0.0075   7.43e-05   -100.805      0.000      -0.008      -0.007
x9             0.0010   4.95e-05     20.414      0.000       0.001       0.001
x10           -0.0035   5.15e-05    -68.782      0.000      -0.004      -0.003
x11           -0.0079   5.42e-05   -145.824      0.000      -0.008      -0.008
x12            0.0062   5.79e-05    107.637      0.000       0.006       0.006
x13           -0.0108   5.69e-05   -189.155      0.000      -0.011      -0.011
x14           -0.0002   5.65e-05     -4.043      0.000      -0.000      -0.000
x15           -0.0133   5.93e-05   -223.663      0.000      -0.013      -0.013
x16           -0.0002   6.31e-05     -3.685      0.000      -0.000      -0.000
x17        -2.798e-09   8.07e-10     -3.468      0.001   -4.38e-09   -1.22e-09
x18           -0.0010   2.58e-05    -38.558      0.000      -0.001      -0.001
x19           -0.0160   6.63e-05   -241.622      0.000      -0.016      -0.016
x20           -0.0057   6.78e-05    -83.469      0.000      -0.006      -0.006
x21            0.0020      7e-05     29.227      0.000       0.002       0.002
x22           -0.0006      0.000     -5.612      0.000      -0.001      -0.000
x23            0.0004   8.04e-05      5.454      0.000       0.000       0.001
x24            0.0005   9.58e-05      5.523      0.000       0.000       0.001
x25            0.0005      0.000      4.332      0.000       0.000       0.001
x26            0.0004      0.000      3.319      0.001       0.000       0.001
x27            0.0015      0.000     11.004      0.000       0.001       0.002
x28            0.0011      0.000      6.325      0.000       0.001       0.001
x29          1.52e-05   7.31e-07     20.794      0.000    1.38e-05    1.66e-05
==============================================================================
Omnibus:                   593907.717   Durbin-Watson:                   1.972
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       5890682278.015
Skew:                          17.570   Prob(JB):                         0.00
Kurtosis:                     706.675   Cond. No.                     1.12e+16
==============================================================================

N

In [ ]:
#splitting the model into training and testing dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_opt,y,test_size=0.2,random_state=0)

In [ ]:
#building and training the model
from sklearn.ensemble import GradientBoostingClassifier
regression = GradientBoostingClassifier(n_estimators=10,random_state=1)
regression.fit(x_train,y_train)

GradientBoostingClassifier(n_estimators=10, random_state=1)

In [ ]:
#predicting the values
y_pred = regression.predict(x_test)
np.set_printoptions(precision=2)
#print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


In [ ]:
#calculation of regression score
r2_score = regression.score(x_test,y_test)
print(r2_score*100,'%')


99.90695551420245 %


In [ ]:
#using cross validation method
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regression, X = x_train, y = y_train, cv = 2)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 99.86 %
Standard Deviation: 0.04 %


In [ ]:
#printing confusion matrix and accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = regression.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[56845    16]
 [   37    64]]


0.9990695551420246